name: Update data for display
on:
  #schedule:
  #  - cron:  '0 8 * * 1'
  push:
    
jobs:
  update-display-data:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2 # Checkout branch into the runner
      - uses: r-lib/actions/setup-r@v2-branch # Set up R
      - uses: r-lib/actions/setup-pandoc@v2 # Set up pandoc for RMD file
          
      - name: Install packages
        run: |
          brew install pkg-config
          R -e 'install.packages("sf")'
          R -e 'install.packages("tidyverse")'
          R -e 'install.packages("lubridate")'
          R -e 'install.packages("leaflet")'
          R -e 'install.packages("rinat")'
          R -e 'install.packages("rebird")'
          R -e 'install.packages("rsconnect")'
          R -e 'install.packages("fullpage")'
          
      - name: Run script to update data
        run: |
          source("display/01_get_app_data.R")
        shell: Rscript {0} 
      
      - name: Commit files # Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git diff-index --quiet HEAD || (git commit -m "daily update for display" && git push)
          
  deploy:
    name: Deploy to shinyapp.io

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install packages
        run: |
          sudo apt-get install fullpage
          
      - name: deploy
        uses: BDSI-Utwente/shinyapps-deploy-github-action@v1
        with:
          # account and application name (https://<accountName>.shinyapps.io/<appName>)
          appName: si_citizen_science_display
          accountName: schoodic-institute-data

          # token and secret obtained from https://www.shinyapps.io/admin/#/tokens
          accountToken: 57B287A6E91E86DCCA29B542392AB8E2
          accountSecret: 6NZ1FD19vvDi6pKIQ+iMXgxiYyTsgOc2yEzTl4bC
