name: Updating Citizen Science Report
run-name: ${{ github.actor }} is updating the report!
on: [push]
  #schedule:
   # - cron:  '40 12 * * 1'
    
jobs:
  Run-Email-Sender-Script:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2 # Checkout branch into the runner
      - uses: r-lib/actions/setup-r@v2-branch # Set up R
      - uses: r-lib/actions/setup-pandoc@v2 # Set up pandoc for RMD file
          
      - name: Install packages
        run: |
          R -e 'install.packages("tidyverse")'
          R -e 'install.packages("lubridate")'
          R -e 'install.packages("kableExtra")'
          R -e 'install.packages("htmltools")'
          
      - name: Run rmd to update info
        run: Rscript -e 'rmarkdown::render(input = "index.Rmd")'
      
      - name: Commit files # Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git diff-index --quiet HEAD || (git commit -m "weekly update of citsci report" && git push)
